apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "temporal-operator.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "temporal-operator.fullname" . }}-serving-cert
  labels:
  {{- include "temporal-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "temporal-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-temporal-io-v1beta1-temporalcluster
  failurePolicy: Fail
  name: mtemporalc.kb.io
  rules:
  - apiGroups:
    - temporal.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - temporalclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "temporal-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-temporal-io-v1beta1-temporalworkerprocess
  failurePolicy: Fail
  name: mtemporalworkerprocess.kb.io
  rules:
  - apiGroups:
    - temporal.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - temporalworkerprocesses
  sideEffects: None