{{- if .Values.webhook.certManager.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "temporal-operator.fullname" . }}-serving-cert
  labels:
  {{- include "temporal-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "temporal-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc'
  - '{{ include "temporal-operator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
  {{- if .Values.webhook.certManager.certificate.useCustomIssuer }}
    {{- toYaml .Values.webhook.certManager.certificate.issuerRef | nindent 4 }}
  {{- else }}
    kind: Issuer
    name: '{{ include "temporal-operator.fullname" . }}-selfsigned-issuer'
  {{- end }}
  secretName: webhook-server-cert
{{- end }}