apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "temporal-operator.fullname" . }}-controller-manager
  labels:
  {{- include "temporal-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.manager.serviceAccount.annotations | nindent 4 }}