apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal-operator.fullname" . }}-webhook-service
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: temporal-operator
    app.kubernetes.io/part-of: temporal-operator
  {{- include "temporal-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.type }}
  selector:
    control-plane: controller-manager
  {{- include "temporal-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhook.ports | toYaml | nindent 2 -}}