apiVersion: temporal.io/v1beta1
kind: TemporalWorkerProcess
metadata:
  name: test
spec:
  version: latest
  replicas: 3
  image: ktenzer/helloworld-worker
  pullPolicy: "Always"
  clusterRef:
    name: prod
    namespace: demo
  temporalNamespace: default
