run:
  timeout: 5m
  issues-exit-code: 2
  tests: false
  skip-dirs:
    - internal/forked
  skip-dirs-use-default: true
  skip-files: []
  modules-download-mode: readonly
  allow-parallel-runners: false
  go: '1.18'
