apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
images:
- name: controller
  newName: controller
  newTag: latest
- name: ghcr.io/alexandrevilain/temporal-operator
  newName: ghcr.io/alexandrevilain/temporal-operator
  newTag: v0.0.1
