---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.alexandrevilain.dev
  resources:
  - temporalclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.alexandrevilain.dev
  resources:
  - temporalclusters/finalizers
  verbs:
  - update
- apiGroups:
  - apps.alexandrevilain.dev
  resources:
  - temporalclusters/status
  verbs:
  - get
  - patch
  - update
