# permissions for end users to view temporalworkerprocesses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: temporalworkerprocess-viewer-role
rules:
- apiGroups:
  - temporal.io
  resources:
  - temporalworkerprocesses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - temporal.io
  resources:
  - temporalworkerprocesses/status
  verbs:
  - get
