# permissions for end users to edit temporalclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: temporalcluster-editor-role
rules:
- apiGroups:
  - apps.alexandrevilain.dev
  resources:
  - temporalclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.alexandrevilain.dev
  resources:
  - temporalclusters/status
  verbs:
  - get
