# permissions for end users to edit temporalappworkers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: temporalappworker-editor-role
rules:
- apiGroups:
  - temporal.io
  resources:
  - temporalappworkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - temporal.io
  resources:
  - temporalappworkers/status
  verbs:
  - get
