apiVersion: v1
kind: Secret
metadata:
  name: postgres-password
  namespace: demo
type: Opaque
data:
  PASSWORD: dGVzdA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: temporal
            - name: POSTGRES_USER
              value: temporal
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: demo
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    service: postgres