name: End2End tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash

env:
  GO_VERSION: 1.19.4
  KIND_VERSION: v0.17.0
  OPERATOR_IMAGE_PATH: /tmp/temporal-operator.tar

jobs:
  run-e2e:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
       kube-version:
       - v1.23.13
       - v1.24.7
       - v1.25.3
       - v1.26.0
    name: Run generate E2E tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: Golang modules cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: temporal-operator:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          outputs: type=docker,dest=${{ env.OPERATOR_IMAGE_PATH }}
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      # e2e-framework uses kind v0.12.0 as default value
      - name: Install kind
        uses: helm/kind-action@v1.5.0
        with:
          version: ${{ env.KIND_VERSION }}
          install_only: true
      - name: Run e2e test suite
        run: make test-e2e
        env:
          OPERATOR_IMAGE_PATH: ${{ env.OPERATOR_IMAGE_PATH }}
          KUBERNETES_VERSION: ${{ matrix.kube-version }}
      - name: Archive operator logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: operator-logs
          path: out/tests/e2e/operator-${{ matrix.kube-version }}.log