name: Publish release on tag

on:
  push:
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  GO_VERSION: "1.20.4"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
      - name: Generate operator hub bundle
        run: make bundle
      - name: Generate release artifacts
        run: make artifacts
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/alexandrevilain/temporal-operator
          tags: |
            type=ref,event=tag
      - name: Docker meta bundle
        id: metabundle
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/alexandrevilain/temporal-operator-bundle
          tags: |
            type=ref,event=tag
      - name: Docker meta example worker-process
        id: workerprocess
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/alexandrevilain/example-worker-process
          tags: |
            type=ref,event=tag
      - name: Build and push operator docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push bundle docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: bundle.Dockerfile
          push: true
          tags: ${{ steps.metabundle.outputs.tags }}
          labels: ${{ steps.metabundle.outputs.labels }}
      - name: Build and push worker-process docker image
        uses: docker/build-push-action@v4
        with:
          context: ./examples/worker-process/helloworld
          push: true
          tags: ${{ steps.workerprocess.outputs.tags }}
          labels: ${{ steps.workerprocess.outputs.labels }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: See [CHANGELOG](https://github.com/alexandrevilain/temporal-operator/blob/main/CHANGELOG.md)
          files: |
            out/release/artifacts/*.yaml
          